name: Generate Release Artifacts (Continuous Integration)
on:
  push:
    paths:
      - '**.FCStd'
  workflow_dispatch:

jobs:
  FCBot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Run FCBot
        uses: asymworks/fcbot@v0
        with:
          dir: output
          config: .fcbot/m23002.yaml
          project: M23002.FCStd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: output
