name: Generate Release Artifacts
on:
  push:
    tags:
      - rev_*
  workflow_dispatch:

jobs:
  FCBot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Run FCBot
        uses: asymworks/fcbot@v0
        with:
          dir: output
          config: .fcbot/m23002.yaml
          project: M23002.FCStd

      - name: Create Release
        uses: softprops/action-gh-release
        with:
          files: |-
            output/**
