name: Generate GitHub README Artifacts (Continuous Integration)
on:
  push:
    paths:
      - '**.FCStd'
  workflow_dispatch:

jobs:
  FCBot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Run FCBot
        uses: asymworks/fcbot@v0
        with:
          dir: assets
          config: .fcbot/snapshot.yaml
          project: M23002.FCStd

      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Documentation Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "asymworks@users.noreply.github.com"
          git add assets
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
